### ISSUE TITLE
client-side timeout can not be detected.

### ISSUE THREAD

**Issue by kgdev** [jshttp/on-finished#13]
When the client side timeouts, the client-side connection is closed. `self.emit('close', isException);` is executed. `ee-first\index.js` will issue `done(err, ee, event, args)` with `event === "close"`. However `function onFinish(error) {` only captures the "error" which is always null.

**Comment by dougwilson** [comment]
Unless you can come up with a way to distinguish this specific event as an error vs a standard connection close, there is nothing we can do.

**Comment by dougwilson** [comment]
Feel free to open a PR with any suggestions :) Please make sure it works across all our supported Node.js versions as well as does not cause false positives on the other conditions.

**Comment by dougwilson** [comment]
If you need this in your own project, you could probably just combine `on-headers` with `on-finished` and simply say "if the response finished before emitting headers, then the client probably terminated the request early"; this wouldn't let you detect the client closing while you are streaming the response, though, but may be good enough for your use-case.

**Comment by kgdev** [comment]
Sounds good. Thanks for the information.

**Comment by kgdev** [comment]
just found that for a normal request/response round trip, the "finish" event is issued instead of"close" event. So it's probably helpful to expose the event in the callback. So that in my application, when I find that a "close" event is issued, it indicates that the connection is closed unexpectedly (by the client).

**Comment by dougwilson** [comment]
> So it's probably helpful to expose the event in the callback. So that in my application, when I find that a "close" event is issued, it indicates that the connection is closed unexpectedly (by the client).

I'm against exposing this kind of implementation detail to the users of this module (especially since this is not documented anywhere in Node.js, so a future version may change this behavior and now my API is screwed). If you are willing to use something like `ee-first` or even just attacking `.on` event listeners, that may be one solution.

Otherwise, if it were to be exposed by this library, then this library should return the `err` populated with a "Request aborted" error to the finished callback, thus hiding Node.js implementation details (especially if the details are not the same across 0.8, 0.10, and 0.12).

I would accept a well-tested PR that does this.

**Comment by cybersky** [comment]
take a look at the "end" event of under-layer socket object:

> Event: 'end'#

`Event: 'end'#
Emitted when the other end of the socket sends a FIN packet.

By default (allowHalfOpen == false) the socket will destroy its file descriptor once it has written out its pending write queue. However, by setting allowHalfOpen == true the socket will not automatically end() its side allowing the user to write arbitrary amounts of data, with the caveat that the user is required to end() their side now.

`

I guess the "end" event will distinguish whether client side close connection positively, which the case client side timeout for most cases.
