### ISSUE TITLE
fires before the end of the response

### ISSUE THREAD

**Issue by martinsson** [jshttp/on-finished#19]
I entered an issue on a downstream project https://github.com/joelabair/multer-autoreap/issues/14 But it appears that the problem comes from this lib. 

sparking this event on socket events rather than solely on the response events is surprising to me. 

It poses a problem when I run selenium tests because they somehow closes the socket way before the request is finished. 

If this is the expected behaviour of the lib, well could I propose MR where I add the possibility to customize what I'm listening on?

**Comment by dougwilson** [comment]
Hi! The purpose of this module is to clean up left behind resources when the response is over (i.e. cannot be sent any longer). If you want to just listen only for the soft response end, that would just be a normal event listed, no? Just write


   res.on('finish', ...)


In your code. You wouldn't even need this module.

The functionality of this module is the first line of the Readme:

> Execute a callback when a HTTP request closes, finishes, or errors.

It just combines together standard Node.js events if you want that specific behavior. If you only want part, just directly listen to the events yourself.

I hope that helps!

**Comment by martinsson** [comment]
The response is not over in my case. The res.socket.emit('close') is fired very early. That is wierd to me but nevertheless it happens whenever the request treatment takes some time AND I use selenium.

**Comment by dougwilson** [comment]
Also, taking a look at that issue, it may be helpful to know that the multer-autoreap is using a very old and buggy version of this module. Perhaps if it is upgraded to the newest version that may improve the issue you are having? Just suggesting :) old versions of this module are not supported, as they have known bugs (which is why new versions have been released). There have been multiple bug fixes on firing too early since the version used by that module.

Anyway, just a thought. But also think about my suggestion before, where if you only want to fire on a specific event, simply lists to that event instead of using this module :) The module only does one thing, and if that does not fit your use-case, I don't see why you'd want to use it :)

**Comment by dougwilson** [comment]
> In particular as is turns out it can be closed before the response is sent.

If the socket is closed, there is literally nothing to write the response bytes to. How can a client get the response?

Perhaps you can provide all the following information and I can take a look? It could be a bug, and so it would help if I can take a look as well.

1. Version of Node.js
2. Version of this module
3. Complete code I can copy and paste and run to reproduce the issue. It must be complete; providing only snippets usually always ends up where I cannot reproduce, as it turns out those parts were triggering the bug.
4. Full instruction on how to call the code provided. Please include a description of what it does when the bug occurs and a description of what you are expecting it to do at that point.

Thank you!

**Comment by martinsson** [comment]
I'll try to do that soon. I started but paused as it was not a tiny bit of code (backend, frontend and selenium tests)

**Comment by joelabair** [comment]
@dougwilson I'll release an update w/ the CV of on-finished referenced ASAP.
