### ISSUE TITLE
EventEmitter raises a warning about potential memory leak when using on-finished with HTTP2 connections

### ISSUE THREAD

**Issue by betalb** [jshttp/on-finished#20]
HTTP2 requests may share one socket, but looking at the code listeners queue is maintained per `msg`

This causes bunch of `error`, `closed` listeners attached to the same socket: [code link](https://github.com/jshttp/on-finished/blob/a5e558be1575e328b50b08cf5c8edaf2851bf5dc/index.js#L114)

**Comment by dougwilson** [comment]
Interesting. Can you share the code and instructions for me to reproduce the issue? Or make a pull request with the suggested fix?

**Comment by dougwilson** [comment]
Hi @betalb, I hope it's OK if I close this. I haven't heard back in a month, so not sure if I'm going to get enough information on what needs to be done here. If you can provide some additional information, I'll happily re-open the issue :) !

**Comment by betalb** [comment]
Sorry for delay, I've created test case: https://github.com/betalb/on-finished-http2

Run server, then client and you will see warnings printed by event emitter

**Comment by dougwilson** [comment]
Hi @betalb cool, I'll take a look. I noticed you're using `.raw` methods, which that project recommends against. Does the issue only occur with `.raw`? In addition, I'm still not quite clear on what the path to resolution would be here, because if you need to know if it's finished and a bunch are on the same socket, Node.js will warn and there is no way around that AFAIK. Node.js warnings were created in a world before http/2 and it being common to multiplex on a socket in Node.js, so, i.m.o, the issue is that the warning is arbitrary and the Node.js core should remove it.

**Comment by betalb** [comment]
I've used `.raw` only to make test case smaller and remove certificate handling code.

According to spec https://http2.github.io/http2-spec/#HttpExtra connection should not be closed by client, until user navigates away from the page.

If I'm not mistaken, callbacks within library for `req` / `res` are queued and only one listener is registered, can't we do the same for socket listeners?

Under normal condition on-finished will fire on `req` / `res` completion and remove listener from socket queue.
