### ISSUE TITLE
[Question] Plz

### ISSUE THREAD

**Issue by Pipikachu** [jshttp/on-finished#25]
Hi, 

I am a javascript learner, When I was read your code, I saw this Code:

```js
var defer = typeof setImmediate === 'function'
  ? setImmediate
  : function (fn) { process.nextTick(fn.bind.apply(fn, arguments)) }
```

I don't understand why you code this:

```js
fn.bind.apply(fn ,arguments)
```

then, I try something to understand this in browser and node env

```js
var a = 6

var ctx = {
    a: 4
}

function Fn() {
    console.log(this.a)
}

Fn.a = 10


function test(fn) {
    fn()
}

test(Fn.bind(this))
test(Fn.bind(ctx))
test(Fn.bind(Fn))
test(Fn.bind.apply(Fn, arguments))
```

I got this result in browser:

```js
>>> 6
>>> 4
>>> 10
>>> Error
```

I got this result in Node

```js
>>> undefined
>>> 4
>>> 10
>>> undefined
```

and then I find when I **console.log** **this** and **arguments** in browser and Node script, I got different answer:

In browser:

```js
console.log(this) // winodw
console.log(arguments) // error
```

In node script:

```js
console.log(this) // {}
console.log(arguments) // {.....} a module object ?
```

I don't know why, Would you help me?  : )

**Comment by dougwilson** [comment]
Hi @Pipikachu the `arguments` keyword is special and only available within a `function`, which is why the browser give the error (and in Node.js it's a module object because it silently wraps all files within an immediately-invoked function expression).

The original function in the code here is the following:
```js
function (fn) { process.nextTick(fn.bind.apply(fn, arguments)) }
```

This creates a function you can call with a function as the first argument and any number of additional arguments to be the arguments into the `fn` function itself after the `process.nextTick` fires. The `apply` is applying the `bind` onto the `fn` + `arguments` in this case, which is used such that the `fn` doesn't need to be removed as the first element in the `arguments` object.

If you're looking for a break down of what this `.bind.apply` does, there are some good break downs on sites like Stackoverflow: https://stackoverflow.com/questions/30754868/what-is-fn-bind-applyfn-arguments-doing

I hope this helps!
