### ISSUE TITLE
Test failed on node version 10 and 11

### ISSUE THREAD

**Issue by derekchuank** [jshttp/on-finished#29]
Looks like `error` event trigger has changed on new version of node .

**Comment by dougwilson** [comment]
Thanks for the report, I will take a look!

**Comment by dougwilson** [comment]
This is due to change of behavior in Node.js 10 that seems unsolvable without changes to Node.js core to restore insight into parser errors.

I filed issues https://github.com/nodejs/node/issues/24586 and https://github.com/nodejs/node/issues/24585

There isn't anything I can really do to fix, unfortunately.

**Comment by dougwilson** [comment]
Per Node.js core: this module will never work on Node.js 10+

**Comment by PixnBits** [comment]
That was an adventure ☹️ 
per https://github.com/nodejs/node/issues/24586#issuecomment-443943085 and https://github.com/expressjs/express/issues/3813#issuecomment-446149979 has this been resolved or is it still a bug?

**Comment by dougwilson** [comment]
Hi @PixnBits sorry about that 😅 So on Node.js 10 (and 11) this module is fixed … but not fixed. So what I mean by that is the test suite for this module still fails on Node.js 9, but on 10 and 11 the test suite does pass, though there are a bunch of edge cases in this module where it doesn't properly detect the finished state. I have been working on a complete re-write of this module to address theses issue and get it working across all the Node.js versions needed for Express.js 4.x in order to get it included in the next Express.js 4.x release.

**Comment by PixnBits** [comment]
Not a problem, thanks so much!
